version: '4.12'

services:
  db-postgres-jwt_auth:
    image: postgres:alpine
    ports: 
      - "5435:5432"
    container_name: "db-postgres-jwt_auth"
    restart: always
    volumes:
      - ./database-jwt_auth:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: renan
      POSTGRES_PASSWORD: renan123

volumes:
    db-postgres-jwt_auth:
