services:
  postgres:
    container_name: jwt_auth
    image: jwt_auth
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD = jwt123
      - POSTGRES_DB = jwt_auth
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  volumes:
    postgres_data:
      