services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: jwt_auth
      POSTGRES_USER: renan
      POSTGRES_PASSWORD: renan123
      PGDATA: /data/postgres_jwt
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=postgres_jwt
      - PGADMIN_LISTEN_PORT = 5050
    ports:
      - "5050:5050"

volumes:
    data:
      external: true